exec-once =  waybar & swaync & awww-daemon

exec-once = sleep 0.5 && wal -i $wpFolder --cols16 --saturate 1 && sleep 0.3 && $wpChange && swaync-client -rs && sleep 0.3 && wal -i $(cat .cache/wal/wal) --cols16 --saturate 1
exec-once = hyprpm reload
exec-once = hyprsunset
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] easyeffects
exec-once = [workspace 3 silent] blueman-manager
exec-once = [workspace special:discord silent] $messenger
exec-once = [workspace special:magic silent] $terminal
exec-once = wl-paste --watch cliphist store

exec-once = hyprctl setcursor breeze_cursors 24

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
