#plugin {
#    hyprexpo {
#        columns = 4
#        gap_size = 5
#        bg_col = rgb(111111)
#        workspace_method = first 1
#
#        gesture_distance = 300
#    }
    # hyprbars {
        # example config
      #  bar_height = 25
        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
       # hyprbars-button = rgba(00000000), 20, 󰖭, hyprctl dispatch killactive
       # hyprbars-button = rgba(00000000), 20, , hyprctl dispatch fullscreen 1
       # hyprbars-button = rgba(00000000), 20, 󰐃, hyprctl dispatch pin
       # bar_color = rgba(101010BB)
       # nobar = true
       # bar_blur = true
       # windowrule= match:float 0, hyprbars:nobars on
   # }
#}
