$terminal = kitty
$fileManager = nemo
$menu = wofi --show drun
$mainMod = SUPER
$wpFolder = ~/wps
$wpChange = awww img "$(cat ~/.cache/wal/wal)" --transition-type any
$browser = firefox
$messenger = discord