source = hypr/variables.conf
source = hypr/autostart.conf
source = hypr/visual.conf
source = hypr/devices.conf
source = hypr/keybinds.conf
source = hypr/plugins.conf
source = hypr/rules.conf

env = XCURSOR_THEME,breeze_cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GDK_SCALE, 1.25