$DISPLAY = eDP-1

general {
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning fingerprint
    }
}

input-field {
    monitor = $DISPLAY
    fade_on_empty = false
    placeholder_text = <i>Enter Password</i>
}

background {
    monitor = $DISPLAY

#  color = rgb(23, 39, 41)
    path = screenshot
    blur_passes = 4
    blur_size = 3
#    brightness = 1
#    contrast = 1
#    vibrancy = 0
}

label {
    monitor = $DISPLAY

#    text = cmd[update:100] echo -e "$FPRINTPROMPT\n$FPRINTFAIL"
    text = $FPRINTPROMPT
    halign = center
    valign = center
    position = 0, -70
}

label {
    monitor = $DISPLAY

    text = $DESC
    halign = center
    valign = center
    position = 0, 70
}
