windowrule = suppress_event maximize, match:class .*

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
windowrule = opacity 0.85, match:class codium
windowrule = no_blur true, match:class codium
windowrule = workspace special:discord silent, match:class $messenger
windowrule = opacity 0.85, match:class obsidian
windowrule = no_blur true, match:class obsidian
windowrule = no_blur true, match:class kitty
layerrule = blur_popups = true, ignore_alpha 0, match:namespace wofi
layerrule = match:namespace waybar, blur off
layerrule = blur on, ignore_alpha 0, match:namespace swaync-control-center, match:namespace swaync-notification-window
layerrule = animation slide top, blur on,ignore_alpha 0.2, match:namespace wofi
layerrule = blur on, ignore_alpha 0, match:namespace swaync-control-center, match:namespace swaync-control-center

windowrule {
    name = kitty-gaps
    match:class = *
    border_size = 0
}
